# encoding: utf-8
require_relative 'main'
require_relative 'employees'
require_relative 'employees_types'
require_relative 'jobs'
require_relative 'trucks'
require_relative 'boxes'
require_relative 'register'
require_relative 'clients'
require_relative 'affectations'
require_relative 'deliveries'
require_relative 'users'
require_relative 'settings'
